name: Docker

on:
  push:
    branches:
      - main
    paths-ignore:
      - web/**
      - doc/**
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  pull_request:
    branches:
      - main
    paths-ignore:
      - web/**
      - doc/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-buildx:
    env:
      IMAGE_NAME: conky
      DOCKER_BUILDKIT: 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      # Build only, no push - this will test that the Dockerfile builds correctly
      # but won't attempt to push to DockerHub
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: conky:latest
