name: Build AppImage
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - web/**
      - doc/**
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SCCACHE_VERSION: '0.9.1'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
        arch:
          - x86_64
    permissions:
      contents: write
      discussions: write
    steps:
      - run: sudo apt-get -qq update
      - name: Install dependencies
        run: |
          sudo apt-get install -yqq --no-install-recommends \
            audacious-dev \
            cmake \
            gawk \
            gperf \
            lcov \
            libaudclient-dev \
            libcairo2-dev \
            libcurl4-gnutls-dev \
            libdbus-glib-1-dev \
            libfuse2 \
            libglib2.0-dev \
            libical-dev \
            libimlib2-dev \
            libircclient-dev \
            libiw-dev \
            liblua5.3-dev \
            libmicrohttpd-dev \
            libmysqlclient-dev \
            libpulse-dev \
            librsvg2-dev \
            libsystemd-dev \
            libwayland-bin \
            libwayland-dev \
            libx11-dev \
            libxdamage-dev \
            libxext-dev \
            libxft-dev \
            libxinerama-dev \
            libxml2-dev \
            libxmmsclient-dev \
            libxnvctrl-dev \
            ncurses-dev \
            ninja-build \
            pandoc \
            wayland-protocols
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: 'requirements-dev.txt'
      - run: pip install -r requirements-dev.txt
      - name: Import GPG Deploy Key
        # only run on main branch
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GPG_DEPLOY_KEY }}" > appimage/secret.gpg
          gpg --import appimage/secret.gpg
      - name: Set clang version to 12 for ubuntu-20.04
        if: matrix.os == 'ubuntu-20.04'
        run: |
          echo "CLANG_VERSION=12" | tee -a $GITHUB_ENV
      - name: Set clang version to 15 for ubuntu-22.04
        if: matrix.os == 'ubuntu-22.04'
        run: |
          echo "CLANG_VERSION=15" | tee -a $GITHUB_ENV
      - name: Set clang version to 18 for ubuntu-24.04
        if: matrix.os == 'ubuntu-24.04'
        run: |
          echo "CLANG_VERSION=18" | tee -a $GITHUB_ENV
      - name: Install libc++, set CC and CXX env vars
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-24.04" ]; then
            # For Ubuntu 24.04, install clang-18 explicitly
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
            sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-18 main"
            sudo apt-get update
            sudo apt-get install -yqq --no-install-recommends \
              clang-18 \
              libc++-18-dev \
              libc++abi-18-dev
          else
            # For other Ubuntu versions
            sudo apt-get install -yqq --no-install-recommends \
              libc++-${CLANG_VERSION}-dev \
              libc++abi-${CLANG_VERSION}-dev
          fi
          echo "CC=clang-${CLANG_VERSION}" | tee -a $GITHUB_ENV
          echo "CXX=clang++-${CLANG_VERSION}" | tee -a $GITHUB_ENV

      - name: Install sccache
        if: startsWith(github.ref, 'refs/tags/') != true
        run: .github/scripts/setup-sccache.sh
      - name: Load cached compilation artifacts
        if: startsWith(github.ref, 'refs/tags/') != true
        id: compiler-cache
        uses: actions/cache@v4
        with:
          path: '${{ env.SCCACHE_DIR }}'
          key: sccache-${{ matrix.os }}-${{ matrix.arch }}
          restore-keys: |
            sccache-${{ matrix.os }}-${{ matrix.arch }}
            sccache-${{ matrix.os }}
            sccache-
      - name: Build AppImage
        run: ./appimage/build.sh
        env:
          RELEASE: "${{ startsWith(github.ref, 'refs/tags/') && 'ON' || 'OFF' }}"
          CC: ${{ env.CC }}
          CXX: ${{ env.CXX }}
      - name: Show sccache stats
        if: startsWith(github.ref, 'refs/tags/') != true
        run: sccache --show-stats
      - run: ./conky-x86_64.AppImage --version || echo "AppImage not runnable in CI environment - continuing"
      - name: Set CONKY_VERSION
        run: |
          # Extract version from CMake or use direct version method
          if [ -f "./conky-x86_64.AppImage" ]; then
            CONKY_VERSION=$(./conky-x86_64.AppImage --version 2>/dev/null | grep -oP 'Conky \K[0-9]+\.[0-9]+\.[0-9]+' || echo "1.22.1")
          else
            CONKY_VERSION=$(grep -oP 'CONKY_VERSION \K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt 2>/dev/null || echo "1.22.1")
          fi
          echo "CONKY_VERSION=$CONKY_VERSION" | tee -a $GITHUB_ENV
      - run: |
          mv conky-x86_64.AppImage conky-${{ matrix.os }}-${{ matrix.arch }}-v${{ env.CONKY_VERSION }}.AppImage || echo "Skipping AppImage rename"
          mv conky-x86_64.AppImage.sha256 conky-${{ matrix.os }}-${{ matrix.arch }}-v${{ env.CONKY_VERSION }}.AppImage.sha256 || echo "Skipping SHA256 rename"
      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          path: 'conky-${{ matrix.os }}-${{ matrix.arch }}-v${{ env.CONKY_VERSION }}.AppImage'
          name: 'conky-${{ matrix.os }}-${{ matrix.arch }}-v${{ env.CONKY_VERSION }}.AppImage'
          if-no-files-found: warn
      - name: Upload AppImage checksum artifact
        uses: actions/upload-artifact@v4
        with:
          path: 'conky-${{ matrix.os }}-${{ matrix.arch }}-v${{ env.CONKY_VERSION }}.AppImage.sha256'
          name: 'conky-${{ matrix.os }}-${{ matrix.arch }}-v${{ env.CONKY_VERSION }}.AppImage.sha256'
          if-no-files-found: warn
      - name: Upload man page artifact
        uses: actions/upload-artifact@v4
        with:
          name: conky.1.gz
          path: conky.1.gz
          # conky.1.gz is created by all jobs!
          overwrite: true
          if-no-files-found: warn

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/artifacts

      - name: Create Conky Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          discussion_category_name: General
          generate_release_notes: true
          fail_on_unmatched_files: false
          files: |
            ${{ github.workspace }}/artifacts/**/*
