name: Web CI

on:
  push:
    branches: [main]
    paths:
      - web/**
      - doc/**
  pull_request:
    branches: [main]
    paths:
      - web/**
      - doc/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
        working-directory: web
      - name: Install missing type dependencies
        run: |
          # Install missing type declarations that might be causing issues
          npm install --save-dev @types/react @types/react-dom @types/node
        working-directory: web
      - name: Lint
        # Continue on error for PRs to prevent blocking merges due to lint issues
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        run: npm run lint
        working-directory: web
      - name: Build
        run: npm run build --if-present
        working-directory: web
      - name: E2E Tests
        run: npm run e2e:headless
        working-directory: web
